language: dart
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_install:
  - git clone https://github.com/flutter/flutter.git -b dev
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter config --enable-web
install:
  - ./flutter/bin/flutter pub get
script:
  - echo success
before_deploy:
  - pub global activate flutterdoc
  - pub global run flutterdoc build
deploy:
  local-dir: flutterdoc_gallery/build/web
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
