name: primer
description: Flutter widgets implementing Primer design system.
version: 0.0.2
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/primer-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Octicons
      fonts:
        - asset: fonts/Octicons.ttf
